"""Add description and keywords to articles

Revision ID: 2f9d329e87a7
Revises: 484ad46d281e
Create Date: 2023-12-07 17:01:15.661273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9d329e87a7'
down_revision = '484ad46d281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('keywords')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
